-- ZYRO Inventario - PostgreSQL 15+
-- Generado desde los 23 TXT. Tablas "inv-*" y atributos "ZYRO_*_#2045_NN".
BEGIN;

CREATE TABLE "inv-empresas" (
  "ZYRO_id_empresa_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_nombre_empresa_#2045_02" VARCHAR(255) NOT NULL,
  "ZYRO_razon_social_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_rfc_#2045_04" VARCHAR(13) NOT NULL,
  "ZYRO_direccion_#2045_05" TEXT,
  "ZYRO_telefono_#2045_06" VARCHAR(255),
  "ZYRO_email_#2045_07" VARCHAR(150),
  "ZYRO_activo_#2045_08" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_fecha_creacion_#2045_09" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_10" DATE NOT NULL,
  "ZYRO_creado_por_usuario_#2045_11" INTEGER NOT NULL,
  "ZYRO_actualizado_por_usuario_#2045_12" INTEGER NOT NULL,
  CONSTRAINT "ck_empresas_rfc" CHECK (char_length("ZYRO_rfc_#2045_04") IN (12,13)),
  CONSTRAINT "ck_empresas_email" CHECK ("ZYRO_email_#2045_07" ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE TABLE "inv-almacenes" (
  "ZYRO_id_almacen_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombre_almacen_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_direccion_#2045_04" TEXT,
  "ZYRO_es_principal_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_activo_#2045_06" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_fecha_creacion_#2045_07" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_08" DATE NOT NULL,
  "ZYRO_creado_por_usuario_#2045_09" INTEGER NOT NULL,
  "ZYRO_actualizado_por_usuario_#2045_10" INTEGER NOT NULL
);

CREATE TABLE "inv-usuarios" (
  "ZYRO_id_usuario_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombres_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_apellido_paterno_#2045_04" VARCHAR(255) NOT NULL,
  "ZYRO_apellido_materno_#2045_05" VARCHAR(255),
  "ZYRO_fecha_nacimiento_#2045_06" DATE,
  "ZYRO_email_#2045_07" VARCHAR(150) NOT NULL,
  "ZYRO_telefono_#2045_08" VARCHAR(255),
  "ZYRO_password_hash_#2045_09" TEXT NOT NULL,
  "ZYRO_activo_#2045_10" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_ultimo_acceso_#2045_11" TIMESTAMP,
  "ZYRO_intentos_fallidos_#2045_12" INTEGER NOT NULL,
  "ZYRO_fecha_bloqueo_#2045_13" TIMESTAMP,
  "ZYRO_id_almacen_defecto_#2045_14" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_fecha_creacion_#2045_15" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_16" DATE NOT NULL,
  "ZYRO_creado_por_usuario_#2045_17" INTEGER NOT NULL,
  "ZYRO_actualizado_por_usuario_#2045_18" INTEGER NOT NULL,
  CONSTRAINT "ck_usuarios_email" CHECK ("ZYRO_email_#2045_07" ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE TABLE "inv-categorias" (
  "ZYRO_id_categoria_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_id_categoria_padre_#2045_03" INTEGER REFERENCES "inv-categorias"("ZYRO_id_categoria_#2045_01"),
  "ZYRO_nombre_categoria_#2045_04" VARCHAR(255) NOT NULL,
  "ZYRO_activo_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "inv-marcas" (
  "ZYRO_id_marca_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombre_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_activo_#2045_04" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "inv-unidades" (
  "ZYRO_id_unidad_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombre_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_abreviatura_#2045_04" VARCHAR(255) NOT NULL,
  "ZYRO_permitir_decimales_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "inv-medidas" (
  "ZYRO_id_medida_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_valor_#2045_02" NUMERIC(18,4) NOT NULL,
  "ZYRO_id_unidad_#2045_03" INTEGER NOT NULL REFERENCES "inv-unidades"("ZYRO_id_unidad_#2045_01"),
  "ZYRO_activo_#2045_04" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_fecha_creacion_#2045_05" DATE NOT NULL,
  CONSTRAINT "ck_medidas_valor" CHECK ("ZYRO_valor_#2045_02" >= 0)
);

CREATE TABLE "inv-productos" (
  "ZYRO_id_producto_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_sku_#2045_03" VARCHAR(100) NOT NULL,
  "ZYRO_codigo_barras_#2045_04" VARCHAR(100) NOT NULL,
  "ZYRO_nombre_producto_#2045_05" VARCHAR(255) NOT NULL,
  "ZYRO_tipo_#2045_06" VARCHAR(255) NOT NULL,
  "ZYRO_descripcion_#2045_07" TEXT NOT NULL,
  "ZYRO_id_marca_#2045_08" INTEGER NOT NULL REFERENCES "inv-marcas"("ZYRO_id_marca_#2045_01"),
  "ZYRO_id_categoria_#2045_09" INTEGER NOT NULL REFERENCES "inv-categorias"("ZYRO_id_categoria_#2045_01"),
  "ZYRO_id_unidad_#2045_10" INTEGER NOT NULL REFERENCES "inv-unidades"("ZYRO_id_unidad_#2045_01"),
  "ZYRO_estatus_#2045_11" VARCHAR(255) NOT NULL,
  "ZYRO_ubicacion_default_#2045_12" VARCHAR(255),
  "ZYRO_en_punto_venta_#2045_13" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_en_catalogo_linea_#2045_14" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_requiere_receta_#2045_15" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_usar_existencias_#2045_16" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_clave_sat_#2045_17" VARCHAR(255),
  "ZYRO_fecha_creacion_#2045_18" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_19" DATE NOT NULL
);

CREATE TABLE "inv-anaqueles" (
  "ZYRO_id_anaquel_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_almacen_#2045_02" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_nombre_anaquel_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_codigo_barras_#2045_04" VARCHAR(100) NOT NULL,
  "ZYRO_activo_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_fecha_creacion_#2045_06" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_07" DATE NOT NULL
);

CREATE TABLE "inv-inventario" (
  "ZYRO_id_inventario_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_producto_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_id_almacen_#2045_03" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_id_anaquel_#2045_04" INTEGER NOT NULL REFERENCES "inv-anaqueles"("ZYRO_id_anaquel_#2045_01"),
  "ZYRO_stock_#2045_05" NUMERIC(18,4) NOT NULL,
  "ZYRO_stock_reorden_#2045_06" NUMERIC(18,4) NOT NULL,
  "ZYRO_stock_critico_#2045_07" NUMERIC(18,4) NOT NULL,
  "ZYRO_stock_maximo_#2045_08" NUMERIC(18,4) NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_09" DATE NOT NULL,
  CONSTRAINT "ck_inventario_stock" CHECK ("ZYRO_stock_#2045_05" >= 0),
  CONSTRAINT "ck_inventario_stock_reorden" CHECK ("ZYRO_stock_reorden_#2045_06" >= 0),
  CONSTRAINT "ck_inventario_stock_critico" CHECK ("ZYRO_stock_critico_#2045_07" >= 0),
  CONSTRAINT "ck_inventario_stock_maximo" CHECK ("ZYRO_stock_maximo_#2045_08" >= 0)
);

CREATE TABLE "inv-listas-precios" (
  "ZYRO_id_lista_precio_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombre_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_es_predeterminado_#2045_04" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_activo_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "inv-productos-precios" (
  "ZYRO_id_precio_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_producto_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_id_lista_precio_#2045_03" INTEGER NOT NULL REFERENCES "inv-listas-precios"("ZYRO_id_lista_precio_#2045_01"),
  "ZYRO_precio_costo_#2045_04" NUMERIC(18,4) NOT NULL,
  "ZYRO_precio_venta_#2045_05" NUMERIC(18,4) NOT NULL,
  "ZYRO_margen_ganancia_#2045_06" NUMERIC(18,4) NOT NULL,
  "ZYRO_fecha_inicio_#2045_07" DATE NOT NULL,
  "ZYRO_fecha_fin_#2045_08" DATE,
  CONSTRAINT "ck_productos_precios_precio_costo" CHECK ("ZYRO_precio_costo_#2045_04" >= 0),
  CONSTRAINT "ck_productos_precios_precio_venta" CHECK ("ZYRO_precio_venta_#2045_05" >= 0),
  CONSTRAINT "ck_productos_precios_margen_ganancia" CHECK ("ZYRO_margen_ganancia_#2045_06" >= 0)
);

CREATE TABLE "inv-producto-imagenes" (
  "ZYRO_id_imagen_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_producto_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_url_imagen_#2045_03" TEXT NOT NULL,
  "ZYRO_es_principal_#2045_04" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_orden_#2045_05" INTEGER NOT NULL
);

CREATE TABLE "inv-componentes-kit" (
  "ZYRO_id_componente_kit_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_producto_kit_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_id_producto_hijo_#2045_03" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_cantidad_#2045_04" NUMERIC(18,4) NOT NULL,
  CONSTRAINT "ck_componentes_kit_cantidad" CHECK ("ZYRO_cantidad_#2045_04" >= 0)
);

CREATE TABLE "inv-permisos" (
  "ZYRO_id_permiso_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_nombre_#2045_02" VARCHAR(255) NOT NULL,
  "ZYRO_modulo_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_descripcion_#2045_04" TEXT NOT NULL,
  "ZYRO_accion_#2045_05" VARCHAR(255) NOT NULL
);

CREATE TABLE "inv-roles" (
  "ZYRO_id_rol_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_nombre_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_descripcion_#2045_04" TEXT NOT NULL,
  "ZYRO_activo_#2045_05" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_fecha_creacion_#2045_06" DATE NOT NULL,
  "ZYRO_fecha_actualizacion_#2045_07" DATE NOT NULL,
  "ZYRO_creado_por_usuario_#2045_08" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01"),
  "ZYRO_actualizado_por_usuario_#2045_09" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01")
);

CREATE TABLE "inv-roles-permisos" (
  "ZYRO_id_rol_#2045_01" INTEGER NOT NULL REFERENCES "inv-roles"("ZYRO_id_rol_#2045_01"),
  "ZYRO_id_permiso_#2045_02" INTEGER NOT NULL REFERENCES "inv-permisos"("ZYRO_id_permiso_#2045_01"),
  PRIMARY KEY ("ZYRO_id_rol_#2045_01", "ZYRO_id_permiso_#2045_02")
);

CREATE TABLE "inv-usuario-roles" (
  "ZYRO_id_usuario_rol_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_usuario_#2045_02" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01"),
  "ZYRO_id_rol_#2045_03" INTEGER NOT NULL REFERENCES "inv-roles"("ZYRO_id_rol_#2045_01"),
  "ZYRO_fecha_asignacion_#2045_04" DATE NOT NULL,
  "ZYRO_fecha_fin_#2045_05" DATE,
  "ZYRO_activo_#2045_06" BOOLEAN NOT NULL DEFAULT TRUE,
  "ZYRO_asignado_por_usuario_#2045_07" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01")
);

CREATE TABLE "inv-tipos-movimiento" (
  "ZYRO_id_tipo_movimiento_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_nombre_#2045_02" VARCHAR(255) NOT NULL,
  "ZYRO_naturaleza_#2045_03" VARCHAR(255) NOT NULL,
  "ZYRO_activo_#2045_04" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "inv-kardex-inventario" (
  "ZYRO_id_movimiento_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_producto_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_id_almacen_#2045_03" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_id_tipo_movimiento_#2045_04" INTEGER NOT NULL REFERENCES "inv-tipos-movimiento"("ZYRO_id_tipo_movimiento_#2045_01"),
  "ZYRO_existencia_#2045_05" NUMERIC(18,4) NOT NULL,
  "ZYRO_cantidad_#2045_06" NUMERIC(18,4) NOT NULL,
  "ZYRO_costo_unitario_#2045_07" NUMERIC(18,4) NOT NULL,
  "ZYRO_observaciones_#2045_08" TEXT NOT NULL,
  "ZYRO_referencia_#2045_09" VARCHAR(100) NOT NULL,
  "ZYRO_fecha_#2045_10" TIMESTAMP NOT NULL,
  "ZYRO_id_usuario_#2045_11" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01"),
  CONSTRAINT "ck_kardex_inventario_existencia" CHECK ("ZYRO_existencia_#2045_05" >= 0),
  CONSTRAINT "ck_kardex_inventario_cantidad" CHECK ("ZYRO_cantidad_#2045_06" >= 0),
  CONSTRAINT "ck_kardex_inventario_costo_unitario" CHECK ("ZYRO_costo_unitario_#2045_07" >= 0)
);

CREATE TABLE "inv-estados-transferencia" (
  "ZYRO_id_estado_transferencia_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_nombre_#2045_02" VARCHAR(255) NOT NULL
);

CREATE TABLE "inv-transferencias" (
  "ZYRO_id_transferencia_#2045_01" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ZYRO_id_empresa_#2045_02" INTEGER NOT NULL REFERENCES "inv-empresas"("ZYRO_id_empresa_#2045_01"),
  "ZYRO_folio_#2045_03" VARCHAR(100) NOT NULL,
  "ZYRO_id_almacen_origen_#2045_04" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_id_almacen_destino_#2045_05" INTEGER NOT NULL REFERENCES "inv-almacenes"("ZYRO_id_almacen_#2045_01"),
  "ZYRO_fecha_solicitud_#2045_06" TIMESTAMP NOT NULL,
  "ZYRO_fecha_autorizacion_#2045_07" TIMESTAMP,
  "ZYRO_fecha_recepcion_#2045_08" TIMESTAMP,
  "ZYRO_id_estado_transferencia_#2045_09" INTEGER NOT NULL REFERENCES "inv-estados-transferencia"("ZYRO_id_estado_transferencia_#2045_01"),
  "ZYRO_observaciones_#2045_10" TEXT NOT NULL,
  "ZYRO_id_usuario_solicita_#2045_11" INTEGER NOT NULL REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01"),
  "ZYRO_id_usuario_autoriza_#2045_12" INTEGER REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01")
);

CREATE TABLE "inv-detalle-transferencia" (
  "ZYRO_id_transferencia_#2045_01" INTEGER NOT NULL REFERENCES "inv-transferencias"("ZYRO_id_transferencia_#2045_01"),
  "ZYRO_id_producto_#2045_02" INTEGER NOT NULL REFERENCES "inv-productos"("ZYRO_id_producto_#2045_01"),
  "ZYRO_cantidad_solicitada_#2045_03" NUMERIC(18,4) NOT NULL,
  "ZYRO_cantidad_enviada_#2045_04" NUMERIC(18,4) NOT NULL,
  "ZYRO_cantidad_recibida_#2045_05" NUMERIC(18,4) NOT NULL,
  PRIMARY KEY ("ZYRO_id_transferencia_#2045_01", "ZYRO_id_producto_#2045_02"),
  CONSTRAINT "ck_detalle_transferencia_cantidad_solicitada" CHECK ("ZYRO_cantidad_solicitada_#2045_03" >= 0),
  CONSTRAINT "ck_detalle_transferencia_cantidad_enviada" CHECK ("ZYRO_cantidad_enviada_#2045_04" >= 0),
  CONSTRAINT "ck_detalle_transferencia_cantidad_recibida" CHECK ("ZYRO_cantidad_recibida_#2045_05" >= 0)
);

ALTER TABLE "inv-empresas" ADD CONSTRAINT "fk_empresas_creado_por_usuario" FOREIGN KEY ("ZYRO_creado_por_usuario_#2045_11") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inv-empresas" ADD CONSTRAINT "fk_empresas_actualizado_por_usuario" FOREIGN KEY ("ZYRO_actualizado_por_usuario_#2045_12") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inv-almacenes" ADD CONSTRAINT "fk_almacenes_creado_por_usuario" FOREIGN KEY ("ZYRO_creado_por_usuario_#2045_09") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inv-almacenes" ADD CONSTRAINT "fk_almacenes_actualizado_por_usuario" FOREIGN KEY ("ZYRO_actualizado_por_usuario_#2045_10") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inv-usuarios" ADD CONSTRAINT "fk_usuarios_creado_por_usuario" FOREIGN KEY ("ZYRO_creado_por_usuario_#2045_17") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inv-usuarios" ADD CONSTRAINT "fk_usuarios_actualizado_por_usuario" FOREIGN KEY ("ZYRO_actualizado_por_usuario_#2045_18") REFERENCES "inv-usuarios"("ZYRO_id_usuario_#2045_01") DEFERRABLE INITIALLY DEFERRED;

COMMIT;
